apiVersion: v1
kind: Service
metadata:
  name: cloudbox-service
spec:
  type: NodePort
  selector:
    app: cloudbox
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30080  # optional: you can omit this and let Kubernetes auto-assign
