name: Build Infrastructure
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Terraform setup
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.10.4

    - name: Install make
      run: sudo apt-get install -y make

    - name: Terraform init
      run: make init

    - name: Terraform fmt
      run: make fmt

    - name: Terraform validate
      run: make validate

    - name: Terraform plan
      run: make plan

    - name: Terraform apply
      run: make up

    # - name: Terraform destroy
    #   run: make down