name: Build Infrastructure
on:
  workflow_dispatch:


 
permissions:
  id-token: write   # Required for OIDC
  contents: read    # Required to clone repo

  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
                
      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          audience: sts.amazonaws.com 
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::902839103466:role/openidconnect

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.4
      
      - name: Building docker image with buildpack
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          chmod +x ./scripts/docker-build.sh
          ./scripts/docker-build.sh

      - name: Push Docker image to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: | 
          echo "Logging in to Docker Hub..."
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push stefnie/cloudbox:latest

      - name: Install make
        run: sudo apt-get install -y make

      - name: Terraform init
        run: make init

      - name: Terraform fmt
        run: make fmt

      - name: Terraform validate
        run: make validate

      - name: Terraform plan
        run: make plan

      - name: Terraform apply
        run: make up

  