name: Build Infrastructure
on:
  workflow_dispatch:


 
permissions:
  id-token: write   # Required for OIDC
  contents: read    # Required to clone repo

  
jobs:
  build:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     python-version: [3.8, 3.9, 3.10, 3.11, 3.12]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # - name: Set up Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: ${{ matrix.python-version }}
      #     cache: 'pip'
      # - uses: advanced-security/python-lint-code-scanning-action@v1
      #   with:
      #     linter: flake8
      #     python-version: ${{ matrix.python-version }}
          
      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          audience: sts.amazonaws.com 
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::902839103466:role/openidconnect

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.4
      
      - name: Building docker image with buildpack
        run: |
          sudo add-apt-repository ppa:cncf-buildpacks/pack-cli
          sudo apt-get update
          sudo apt-get install pack-cli
          cd myapp
          pack build myapp:latest \
          --builder paketo-buildpacks/builder:base
  
      - name: Install make
        run: sudo apt-get install -y make

      - name: Terraform init
        run: make init

      - name: Terraform fmt
        run: make fmt

      - name: Terraform validate
        run: make validate

      - name: Terraform plan
        run: make plan

      # - name: Terraform apply
      #   run: make up

  