name: Build Infrastructure
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11, 3.12]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: flake8
          python-version: ${{ matrix.python-version }}
          
      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          audience: sts.amazonaws.com 
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.IAM_ROLE }}

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.4
      
      - name: Building docker image with buildpack
        run: |
          sudo add-apt-repository ppa:cncf-buildpacks/pack-cli
          sudo apt-get update
          sudo apt-get install pack-cli
          cd myapp
          pack build myapp:latest \
          --builder paketo-buildpacks/builder:base
  
      - name: Install make
        run: sudo apt-get install -y make

      - name: Terraform init
        run: make init

      - name: Terraform fmt
        run: make fmt

      - name: Terraform validate
        run: make validate

      - name: Terraform plan
        run: make plan

      - name: Terraform apply
        run: make up

  